name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - uses: gradle/wrapper-validation-action@v2
      - uses: gradle/gradle-build-action@v3
      - name: Build & Test
        run: ./gradlew --no-daemon clean test jacocoTestReport
      - name: Upload reports (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-reports
          path: |
            **/build/reports/tests/test
            **/build/reports/jacoco/test/html
            **/build/reports/jacoco/test/jacocoTestReport.xml
          if-no-files-found: warn
